### PR TITLE
Added Group `init`

### PR DESCRIPTION
**Pull request by RichardLitt**
Because I can!

### CODE REVIEW

**Comment by daviddias** [comment]
We don't need to add parts of core-api that are not parts of the http-api

**Comment by RichardLitt** [comment]
Isn't it better to be inclusive?

**Comment by RichardLitt** [comment]
@jbenet What do you think?

**Comment by daviddias** [comment]
That should go here:

https://github.com/ipfs/specs/blob/master/api/cli/README.md

and its programmatic counterpart

https://github.com/ipfs/specs/tree/master/api/core

**Pull request closed without merging**
