### PR TITLE
update the readme description

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Let's add a link to the apiary version as well

**Comment by daviddias** [comment]
@Dignifiedquire added :)

**Comment by dignifiedquire** [comment]
LGTM

**Comment by daviddias** [comment]
thank you :)

**Comment by RichardLitt** [comment]
@diasdavid Why did you remove the contribute banner?

Did you update the tagline? The `>` section should match the GitHub description for the repo, so it can't be this long. 

:-1: to this PR.

**Comment by daviddias** [comment]
@RichardLitt the contribute banner is on line 20 and now links to the contributing guide on ipfs/community, check https://github.com/ipfs/api#wanna-hack-on-ipfs

**Comment by RichardLitt** [comment]
ahaha, bam. Missed that. Thanks! Ok, this is OK then. :)

**Pull request merged**
