### PR TITLE
Added Group `mount`

### PR DESCRIPTION
**Pull request by RichardLitt**
This didn't work. At all.

### CODE REVIEW

**Comment by daviddias** [comment]
**bold**

**Comment by RichardLitt** [comment]
?

**Comment by daviddias** [comment]
I meant that, the "Group mount" is probably the more complex and unstable so far, so you were very courageous digging on it already :)

**Comment by RichardLitt** [comment]
Well, it's what I've got to work with. What do you think? Merge? It reflects the current state.

**Comment by daviddias** [comment]
merging sounds good, might want to add a note saying it is "unstable" at the top.

**Comment by RichardLitt** [comment]
Woot!

**Pull request merged**
