### PR TITLE
Added Group `version`

### PR DESCRIPTION
**Pull request by RichardLitt**
I was unable to get get any of the three options working. Are they available, @whyrusleeping?

### CODE REVIEW

**Comment by daviddias** [comment]
They are probably just CLI level options, try to sniff the 3 through wire shark, if the request/response are the same, it means it is the CLI that is doing the parsing and filtering (which means the flags shouldn't be described on the HTTP-API)

**Comment by RichardLitt** [comment]
They don't even hit wireshark. I think this is all done on the API. So; I guess I should remove those options?

**Comment by daviddias** [comment]
Yep, that is correct :)

**Comment by RichardLitt** [comment]
Thanks @diasdavid

**Comment by RichardLitt** [comment]
This is for #20

**Pull request merged**
