### PR TITLE
Added apiary file

### PR DESCRIPTION
**Pull request by RichardLitt**
The Readme Dignifiedquire/ipfs-http-api is empty, and the license is MIT, which
I am not sure we are going with here.

This move is in reference to #11.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
I don't mind what license but we should have one specified

**Comment by jbenet** [comment]
MIT pls

**Comment by RichardLitt** [comment]
License added.

**Comment by dignifiedquire** [comment]
:+1:

**Comment by RichardLitt** [comment]
Removed the old files and edited the README, too.

**Comment by dignifiedquire** [comment]
@RichardLitt you should make a PR then to specs with those files so they are not lost though?

**Comment by RichardLitt** [comment]
@Dignifiedquire Already merged: https://github.com/ipfs/specs/pull/51

**Comment by dignifiedquire** [comment]
cool then lets merge this

**Pull request merged**
