### PR TITLE
Added Group `files`

### PR DESCRIPTION
**Pull request by RichardLitt**
Current issues that should be resolved first: 
- [x] https://github.com/ipfs/go-ipfs/issues/2378

### CODE REVIEW

**Comment by RichardLitt** [comment]
Note https://github.com/ipfs/go-ipfs/pull/2423

**Comment by RichardLitt** [comment]
@diasdavid or @dignifiedquire, want to take a crack at reviewing this?

**Comment by daviddias** [comment]
@RichardLitt what is missing here for the merge?

**Comment by RichardLitt** [comment]
@diasdavid It needs review.

**Pull request merged**
